# Generated by Django 3.2.9 on 2021-11-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_iletisimmodel_yazilarmodel_yorummodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazilarmodel',
            old_name='duzenleme_tarihi',
            new_name='duzenlenme_tarihi',
        ),
        migrations.RenameField(
            model_name='yorummodel',
            old_name='duzenleme_tarihi',
            new_name='duzenlenme_tarihi',
        ),
        migrations.AlterField(
            model_name='yazilarmodel',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='yorummodel',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
